### ISSUE TITLE
UI Todo

### ISSUE THREAD

**Issue by windowdong11** [windowdong11/blackjack-client#3]
UI Todo

- [x] 네비게이션 바 구현 
- [x] 아이콘 선정 
- [ ] 홈 페이지 개선
- [ ] 로그인 페이지 개선
- [ ] 회원가입 페이지 개선
- [ ] 채팅 페이지 개선
- [ ] HowTo 페이지 작성
